### ISSUE TITLE
access kwargs in non builtin functions

### ISSUE THREAD

**Issue by jstoebel** [beeware/batavia#564]
In non builtin functions, key word arguments are not accessible.

To reproduce:

 - add a method to a datatype. For example:

```
Str.prototype.format = function(args, kwargs) { 
    // a trivial example
    return kwargs;
}
```

when you try running `print('hello {planet}'.format(planet='world'))` in the testbed, the result is `None`. If you add `console.log(arguments)` there are zero arguments.

PS: I hope I'm not a bother by adding this ticket as well as asking in Gitter. As there was not an immediate answer available in Gitter I thought it would be helpful to move it to a more permanent place.

**Comment by freakboy3742** [comment]
@jstoebel No bother at all - opening a ticket if you don't get a response on Gitter is an entirely reasonable response.

I can't offer any obvious answer why this is failing; If I had to guess, it's likely because the invocation is "keywords only" -  invoking ``format(x=123)`` is a different opcode to ``format(123)``, and the former isn't used as often. If you want to go digging, the opcode implementation is ``byte_CALL_FUNCTION_KW`` in VirtualMachine.js.

**Comment by abonie** [comment]
@jstoebel does this line:
```javascript
Str.prototype.format.$pyargs = true
```
 fix your problem?

**Comment by jstoebel** [comment]
@abonie thanks for your reply. I'm confused, how should I implement this method to have access to `kwargs`?

**Comment by abonie** [comment]
@jstoebel so I just checked and if you add this line after your method definition it should make it so that it uses Batavia calling convention, e.g.
```javascript
Str.prototype.format = function(args, kwargs) { 
    // a trivial example
    return kwargs;
}

Str.prototype.format.$pyargs = true
```
kwargs in this case will be a JSDict object containing keyword arguments, your example: `print('hello {planet}'.format(planet='world'))` will print `{'planet': 'world'}`.


Now, if anyone could explain how to make kwargs work for class instantiation, I would be very grateful :)

**Comment by jstoebel** [comment]
Thanks! @freakboy3742 is this a satisfactory resolution to this issue?

**Comment by martica** [comment]
Looks like this is resolved. Functions need to be marked as $pyargs to get called with args and kwargs as a list and a dict.
